#!/usr/bin/env python3
"""Converts the input-prompt SVGs in this folder into Android VectorDrawables.

    python3 art/input/convert-input-art.py

Writes app/src/main/res/drawable/<name>.xml, one per SVG. The generated files are committed, so
this only needs running when the art changes — it is a dev tool, not a build step.

The conversion is a text transform rather than a real SVG renderer, and it can be because Kenney's
Input Prompts are uniformly simple: a 64x64 canvas, one or two <path> elements, no strokes, a solid
hex fill, and path data using only M, L and Q. All three commands are valid android:pathData as-is,
so the geometry is copied across untouched.

That simplicity is an assumption, not a guarantee. Every SVG is checked against it below and the
script refuses anything it would silently mangle — a gradient, a transform or a stroke would
otherwise convert into a drawable that renders wrong rather than not at all.
"""
import re
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
# parents[1] is art/, parents[2] the repo root. See the note in art/icon/generate-launcher-icons.py:
# the assert is what stops a future move from quietly writing the drawables into the wrong tree.
ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "app/src/main/res/drawable"

assert (ROOT / "settings.gradle.kts").exists(), f"{ROOT} is not the repo root; fix the path above"

SVG_NS = "{http://www.w3.org/2000/svg}"

# Only these path commands survive the copy. Anything else — arcs, cubics, the relative forms — is
# still valid SVG and still valid pathData, but it has not been eyeballed against this art, so fail
# rather than assume.
ALLOWED_COMMANDS = set("MLQ")

TEMPLATE = """<!-- Generated by art/input/convert-input-art.py from {source}. Do not edit.
     Kenney Input Prompts 1.5A, CC0 — see art/input/kenney-input-prompts-LICENSE.txt -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{size}"
    android:viewportHeight="{size}">
{paths}
</vector>
"""

PATH = """    <path
        android:fillColor="{fill}"
        android:pathData="{data}" />"""


def convert(svg_path: Path) -> str:
    """The VectorDrawable XML for one SVG, or raise if it uses anything unsupported."""
    root = ET.parse(svg_path).getroot()

    width, height = root.get("width"), root.get("height")
    if width != height:
        raise SystemExit(f"{svg_path.name}: canvas is {width}x{height}, expected square")

    # Groups are allowed only as plain containers. A transform on one would move its children, and
    # copying the paths out from under it would silently shift the art.
    for group in root.iter(f"{SVG_NS}g"):
        if group.get("transform"):
            raise SystemExit(f"{svg_path.name}: <g> has a transform, which this script drops")

    paths = []
    for element in root.iter(f"{SVG_NS}path"):
        fill = element.get("fill", "#000000")
        if not re.fullmatch(r"#[0-9A-Fa-f]{6}", fill):
            raise SystemExit(f"{svg_path.name}: fill {fill!r} is not a solid hex colour")

        stroke = element.get("stroke", "none")
        if stroke != "none":
            raise SystemExit(f"{svg_path.name}: stroke {stroke!r} is not carried over")

        data = element.get("d", "").strip()
        commands = set(re.findall(r"[A-Za-z]", data))
        if not commands <= ALLOWED_COMMANDS:
            unsupported = "".join(sorted(commands - ALLOWED_COMMANDS))
            raise SystemExit(f"{svg_path.name}: path uses unchecked commands {unsupported!r}")

        paths.append(PATH.format(fill=fill, data=data))

    if not paths:
        raise SystemExit(f"{svg_path.name}: no <path> elements found")

    return TEMPLATE.format(source=svg_path.name, size=width, paths="\n".join(paths))


def main() -> None:
    sources = sorted(HERE.glob("*.svg"))
    if not sources:
        raise SystemExit(f"no SVGs in {HERE}")

    RES.mkdir(parents=True, exist_ok=True)
    for svg_path in sources:
        (RES / f"{svg_path.stem}.xml").write_text(convert(svg_path))

    print(f"  {len(sources)} drawables -> {RES.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
